# Archivo generado automáticamente: respaldo embebido de las plantillas del scanner.
# Permite que TALMA/POLICÍA funcionen incluso si Render/GitHub no copia la carpeta templates.

SCANNER_TEMPLATES = {'calibrar.html': '<!doctype html>\n'
                  '<html lang="es">\n'
                  '<head>\n'
                  '<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n'
                  '<title>Ajustar columnas · {{ titulo }}</title><link rel="stylesheet" '
                  'href="/admin/scanner-style.css">\n'
                  '</head>\n'
                  '<body>\n'
                  '<nav class="admin-nav">\n'
                  '  <a href="/admin/dashboard">Pedidos</a>\n'
                  '  <a href="/admin/talma/" class="{% if sistema==\'talma\' %}active{% endif %}">TALMA</a>\n'
                  '  <a href="/admin/policia/" class="{% if sistema==\'policia\' %}active{% endif %}">POLICÍA</a>\n'
                  '  <a class="logout" href="/admin/logout">Cerrar sesión</a>\n'
                  '</nav>\n'
                  '<main class="calibration-page">\n'
                  '  <header class="calibration-header">\n'
                  '    <div>\n'
                  '      <div class="system-kicker">SCANNER {{ titulo }}</div>\n'
                  '      <h1>Ajusta las tres líneas</h1>\n'
                  '      <p>Coloca cada línea al inicio de la columna indicada. Así no se mezclan los campos.</p>\n'
                  '    </div>\n'
                  '    <div style="display:flex;gap:8px;flex-wrap:wrap">\n'
                  '      <a class="button secondary" href="/admin/{{ sistema }}/">Otra imagen</a>\n'
                  '      <a class="button secondary" href="/admin/dashboard">Pedidos</a>\n'
                  '    </div>\n'
                  '  </header>\n'
                  '\n'
                  '  <div class="calibration-legend">\n'
                  '    <span>1. Inicio de {{ label_entrada }}</span>\n'
                  '    <span>2. Inicio de {{ label_segundo }}</span>\n'
                  '    <span>3. Inicio de {{ label_observacion }}</span>\n'
                  '  </div>\n'
                  '\n'
                  '  <div id="stage" class="image-stage">\n'
                  '    <img id="sourceImage" src="/admin/scanner-imagen/{{ filename }}" alt="Captura para calibrar">\n'
                  '    <div class="guide guide-entry" data-key="entry" style="left:{{ entry_start * 100 }}%"><b>{{ '
                  'label_entrada }}</b></div>\n'
                  '    <div class="guide guide-second" data-key="second" style="left:{{ second_start * 100 }}%"><b>{{ '
                  'label_segundo }}</b></div>\n'
                  '    <div class="guide guide-observation" data-key="observation" style="left:{{ observation_start * '
                  '100 }}%"><b>{{ label_observacion }}</b></div>\n'
                  '  </div>\n'
                  '\n'
                  '  <form method="post" action="/admin/{{ sistema }}/procesar" id="calibrationForm" class="card '
                  'calibration-form">\n'
                  '    <input type="hidden" name="filename" value="{{ filename }}">\n'
                  '    <input type="hidden" name="entry_start" id="entry_start" value="{{ entry_start }}">\n'
                  '    <input type="hidden" name="second_start" id="second_start" value="{{ second_start }}">\n'
                  '    <input type="hidden" name="observation_start" id="observation_start" value="{{ '
                  'observation_start }}">\n'
                  '    <button type="submit">Leer pedidos con estas columnas</button>\n'
                  '  </form>\n'
                  '</main>\n'
                  '<script>\n'
                  "const stage = document.getElementById('stage');\n"
                  "const guides = [...document.querySelectorAll('.guide')];\n"
                  "const ids = {entry:'entry_start', second:'second_start', observation:'observation_start'};\n"
                  '\n'
                  'guides.forEach(guide => {\n'
                  '  let dragging = false;\n'
                  "  guide.addEventListener('pointerdown', event => {\n"
                  '    dragging = true;\n'
                  '    guide.setPointerCapture(event.pointerId);\n'
                  '  });\n'
                  "  guide.addEventListener('pointermove', event => {\n"
                  '    if (!dragging) return;\n'
                  '    const rect = stage.getBoundingClientRect();\n'
                  '    let ratio = (event.clientX - rect.left) / rect.width;\n'
                  '    ratio = Math.max(0.05, Math.min(0.98, ratio));\n'
                  '    const ordered = guides.map(g => ({g, key:g.dataset.key, r:parseFloat(g.style.left)/100}));\n'
                  '    const index = ordered.findIndex(x => x.g === guide);\n'
                  '    const min = index > 0 ? ordered[index - 1].r + 0.01 : 0.05;\n'
                  '    const max = index < ordered.length - 1 ? ordered[index + 1].r - 0.01 : 0.98;\n'
                  '    ratio = Math.max(min, Math.min(max, ratio));\n'
                  '    guide.style.left = `${ratio * 100}%`;\n'
                  '    document.getElementById(ids[guide.dataset.key]).value = ratio.toFixed(5);\n'
                  '  });\n'
                  "  guide.addEventListener('pointerup', () => dragging = false);\n"
                  "  guide.addEventListener('pointercancel', () => dragging = false);\n"
                  '});\n'
                  '</script>\n'
                  '</body>\n'
                  '</html>\n',
 'error.html': '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" '
               'content="width=device-width,initial-scale=1"><title>Error</title><link rel="stylesheet" '
               'href="/admin/scanner-style.css"></head>\n'
               '<body><nav class="admin-nav"><a href="/admin/dashboard">Pedidos</a><a href="/admin/talma/">TALMA</a><a '
               'href="/admin/policia/">POLICÍA</a><a class="logout" href="/admin/logout">Cerrar sesión</a></nav><main '
               'class="container"><section class="card error"><h1>No se pudo procesar la '
               'imagen</h1><p>{{message}}</p>{% if detail %}<details><summary>Ver detalle '
               'técnico</summary><pre>{{detail}}</pre></details>{% endif %}<a class="button" '
               'href="/admin/scanners">Volver a scanners</a></section></main></body></html>\n',
 'index.html': '<!doctype html>\n'
               '<html lang="es"><head><meta charset="utf-8"><meta name="viewport" '
               'content="width=device-width,initial-scale=1"><title>Scanners · Panel administrador</title><link '
               'rel="stylesheet" href="/admin/scanner-style.css"></head>\n'
               '<body>\n'
               '<nav class="admin-nav"><a href="/admin/dashboard">Pedidos</a><a href="/admin/talma/">TALMA</a><a '
               'href="/admin/policia/">POLICÍA</a><a class="logout" href="/admin/logout">Cerrar sesión</a></nav>\n'
               '<main class="container"><h1>Scanners de cuponeras</h1><p class="subtitle">Selecciona TALMA o '
               'POLICÍA.</p>\n'
               '<div class="systems"><section class="system-card talma"><span class="badge '
               'talma">TALMA</span><h2>Panel TALMA</h2><p>Scanner, calibración, revisión, PDF y Excel.</p><a '
               'class="button" href="/admin/talma/">Abrir TALMA</a></section><section class="system-card '
               'policia"><span class="badge policia">POLICÍA</span><h2>Panel POLICÍA</h2><p>Scanner PNP, calibración, '
               'revisión, PDF y Excel.</p><a class="button" href="/admin/policia/">Abrir POLICÍA</a></section></div>\n'
               '</main></body></html>\n',
 'revisar_policia.html': '<!doctype html>\n'
                         '<html lang="es">\n'
                         '<head>\n'
                         '<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n'
                         '<title>Revisar pedidos POLICÍA</title><link rel="stylesheet" '
                         'href="/admin/scanner-style.css">\n'
                         '<style>table{min-width:1400px}td:nth-child(3) input{min-width:320px}td:nth-child(4) '
                         'input{min-width:220px}td:nth-child(5) input{min-width:260px}td:nth-child(6) '
                         'input{min-width:200px}</style>\n'
                         '</head>\n'
                         '<body>\n'
                         '<nav class="admin-nav">\n'
                         '  <a href="/admin/dashboard">Pedidos</a><a href="/admin/talma/">TALMA</a><a '
                         'href="/admin/policia/" class="active">POLICÍA</a><a class="logout" '
                         'href="/admin/logout">Cerrar sesión</a>\n'
                         '</nav>\n'
                         '<main class="table-page">\n'
                         '<header class="toolbar">\n'
                         '  <div><div class="system-kicker">PANEL POLICÍA</div><h1>{{ rows|length }} pedidos '
                         'POLICÍA</h1><p>Entrada · Plato de fondo · Sugerencias. Las tildes y la ñ se '
                         'conservan.</p></div>\n'
                         '  <div class="buttons">\n'
                         '    <button onclick="guardar()">Guardar cambios</button>\n'
                         '    <a class="button" href="/admin/policia/pdf">Generar PDF</a>\n'
                         '    <a class="button secondary" href="/admin/policia/excel">Generar Excel mensual</a>\n'
                         '    <button type="button" class="secondary" onclick="abrirActualizacion()">Actualizar Excel '
                         'mensual</button>\n'
                         '    <a class="button secondary" href="/admin/policia/calibrar/{{ filename }}">Ajustar '
                         'columnas</a>\n'
                         '    <a class="button secondary" href="/admin/policia/">Nueva imagen</a>\n'
                         '  </div>\n'
                         '</header>\n'
                         '<table id="tabla"><thead><tr><th>Estado</th><th>N°</th><th>Nombre y '
                         'apellido</th><th>Entrada</th><th>Plato de '
                         'fondo</th><th>Sugerencias</th></tr></thead><tbody>\n'
                         '{% for r in rows %}<tr class="{% if r._warnings %}warning{% endif %}">\n'
                         '<td title="{{r._warnings|join(\', \')}}">{% if r._warnings %}⚠{% else %}{% endif %}</td>\n'
                         '<td><input data-col="numero" value="{{r.numero}}" style="width:60px"></td><td><input '
                         'data-col="nombre" value="{{r.nombre}}"></td><td><input data-col="entrada" '
                         'value="{{r.entrada}}"></td><td><input data-col="segundo" '
                         'value="{{r.segundo}}"></td><td><input data-col="observacion" '
                         'value="{{r.observacion}}"></td>\n'
                         '</tr>{% endfor %}\n'
                         '</tbody></table>\n'
                         '<section id="actualizar-excel" class="excel-update" hidden>\n'
                         '  <h2>Actualizar el Excel mensual POLICÍA</h2><p>Selecciona el archivo .xlsx del mes. Los '
                         'pedidos actuales se agregarán debajo de los anteriores.</p>\n'
                         '  <form method="post" action="/admin/policia/actualizar-excel" '
                         'enctype="multipart/form-data">\n'
                         '    <label>Excel mensual a actualizar</label><input type="file" name="excel_anterior" '
                         'accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required>\n'
                         '    <button type="submit">Agregar pedidos al Excel mensual</button><button type="button" '
                         'class="secondary" onclick="cerrarActualizacion()">Cancelar</button>\n'
                         '  </form>\n'
                         '</section>\n'
                         '<p id="message"></p>\n'
                         '</main>\n'
                         '<script>\n'
                         'function '
                         "abrirActualizacion(){document.getElementById('actualizar-excel').hidden=false;document.getElementById('actualizar-excel').scrollIntoView({behavior:'smooth',block:'center'});}\n"
                         "function cerrarActualizacion(){document.getElementById('actualizar-excel').hidden=true;}\n"
                         'async function guardar(){\n'
                         " const rows=[...document.querySelectorAll('#tabla tbody tr')].map(tr=>{const "
                         "row={};tr.querySelectorAll('[data-col]').forEach(el=>row[el.dataset.col]=el.value);return "
                         'row;});\n'
                         " const form=new FormData();form.append('rows_json',JSON.stringify(rows));\n"
                         " const response=await fetch('/admin/policia/guardar',{method:'POST',body:form});const "
                         'data=await response.json();\n'
                         " document.getElementById('message').textContent=`Se guardaron ${data.count} pedidos "
                         'POLICÍA.`;\n'
                         '}\n'
                         '</script>\n'
                         '</body></html>\n',
 'revisar_talma.html': '<!doctype html>\n'
                       '<html lang="es">\n'
                       '<head>\n'
                       '<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n'
                       '<title>Revisar pedidos TALMA</title><link rel="stylesheet" href="/admin/scanner-style.css">\n'
                       '</head>\n'
                       '<body>\n'
                       '<nav class="admin-nav">\n'
                       '  <a href="/admin/dashboard">Pedidos</a><a href="/admin/talma/" class="active">TALMA</a><a '
                       'href="/admin/policia/">POLICÍA</a><a class="logout" href="/admin/logout">Cerrar sesión</a>\n'
                       '</nav>\n'
                       '<main class="table-page">\n'
                       '<header class="toolbar">\n'
                       '  <div><div class="system-kicker">PANEL TALMA</div><h1>{{ rows|length }} pedidos '
                       'TALMA</h1><p>Revisa las filas amarillas antes de imprimir.</p></div>\n'
                       '  <div class="buttons">\n'
                       '    <button onclick="guardar()">Guardar cambios</button>\n'
                       '    <a class="button" href="/admin/talma/pdf">Generar PDF</a>\n'
                       '    <a class="button secondary" href="/admin/talma/excel">Generar Excel mensual</a>\n'
                       '    <button type="button" class="secondary" onclick="abrirActualizacion()">Actualizar Excel '
                       'mensual</button>\n'
                       '    <a class="button secondary" href="/admin/talma/calibrar/{{ filename }}">Ajustar '
                       'columnas</a>\n'
                       '    <a class="button secondary" href="/admin/talma/">Nueva imagen</a>\n'
                       '  </div>\n'
                       '</header>\n'
                       '<table id="tabla">\n'
                       '<thead><tr><th>Estado</th><th>Registro</th><th>Fecha</th><th>Sede</th><th>Código</th><th>Nombre</th><th>Área</th><th>Entrada</th><th>Segundo</th><th>Observación</th></tr></thead>\n'
                       '<tbody>\n'
                       '{% for r in rows %}\n'
                       '<tr class="{% if r._warnings %}warning{% endif %}">\n'
                       '<td title="{{r._warnings|join(\', \')}}">{% if r._warnings %}⚠{% else %}{% endif %}</td>\n'
                       "{% for col in ['registro','fecha','sede','codigo','nombre'] %}<td><input "
                       'data-col="{{col}}" value="{{r[col]}}"></td>{% endfor %}\n'
                       '<td><select data-col="area"><option></option>{% for a in areas %}<option {% if r.area==a '
                       '%}selected{% endif %}>{{a}}</option>{% endfor %}</select></td>\n'
                       '{% for col in [\'entrada\',\'segundo\',\'observacion\'] %}<td><input data-col="{{col}}" '
                       'value="{{r[col]}}"></td>{% endfor %}\n'
                       '</tr>\n'
                       '{% endfor %}\n'
                       '</tbody></table>\n'
                       '<section id="actualizar-excel" class="excel-update" hidden>\n'
                       '  <h2>Actualizar el Excel mensual</h2><p>Selecciona el archivo .xlsx del mes. Los pedidos '
                       'actuales se agregarán debajo de los anteriores.</p>\n'
                       '  <form method="post" action="/admin/talma/actualizar-excel" enctype="multipart/form-data">\n'
                       '    <label>Excel mensual a actualizar</label><input type="file" name="excel_anterior" '
                       'accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required>\n'
                       '    <button type="submit">Agregar pedidos al Excel mensual</button><button type="button" '
                       'class="secondary" onclick="cerrarActualizacion()">Cancelar</button>\n'
                       '  </form>\n'
                       '</section>\n'
                       '<p id="message"></p>\n'
                       '</main>\n'
                       '<script>\n'
                       'function '
                       "abrirActualizacion(){document.getElementById('actualizar-excel').hidden=false;document.getElementById('actualizar-excel').scrollIntoView({behavior:'smooth',block:'center'});}\n"
                       "function cerrarActualizacion(){document.getElementById('actualizar-excel').hidden=true;}\n"
                       'async function guardar(){\n'
                       " const rows=[...document.querySelectorAll('#tabla tbody tr')].map(tr=>{const "
                       "row={};tr.querySelectorAll('[data-col]').forEach(el=>row[el.dataset.col]=el.value);return "
                       'row;});\n'
                       " const form=new FormData();form.append('rows_json',JSON.stringify(rows));\n"
                       " const response=await fetch('/admin/talma/guardar',{method:'POST',body:form});const data=await "
                       'response.json();\n'
                       " document.getElementById('message').textContent=`Se guardaron ${data.count} pedidos TALMA.`;\n"
                       '}\n'
                       '</script>\n'
                       '</body></html>\n',
 'subir.html': '<!doctype html>\n'
               '<html lang="es">\n'
               '<head>\n'
               '<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n'
               '<title>{{ titulo }} · Panel administrador</title><link rel="stylesheet" '
               'href="/admin/scanner-style.css">\n'
               '</head>\n'
               '<body>\n'
               '<nav class="admin-nav">\n'
               '  <a href="/admin/dashboard">Pedidos</a>\n'
               '  <a href="/admin/talma/" class="{% if sistema==\'talma\' %}active{% endif %}">TALMA</a>\n'
               '  <a href="/admin/policia/" class="{% if sistema==\'policia\' %}active{% endif %}">POLICÍA</a>\n'
               '  <a class="logout" href="/admin/logout">Cerrar sesión</a>\n'
               '</nav>\n'
               '<main class="container">\n'
               '  <div class="system-kicker">SCANNER {{ titulo }}</div>\n'
               '  <h1>Panel {{ titulo }}</h1>\n'
               '  <p class="subtitle">{{ subtitulo }}</p>\n'
               '  <section class="card">\n'
               '    <h2>Escanear una planilla</h2>\n'
               '    <form method="post" action="/admin/{{ sistema }}/subir" enctype="multipart/form-data">\n'
               '      <label>Captura del pedido</label>\n'
               '      <input type="file" name="imagen" accept="image/png,image/jpeg,image/webp" required>\n'
               '      <button type="submit">Cargar imagen y calibrar</button>\n'
               '    </form>\n'
               '  </section>\n'
               '  <section class="info">{{ ayuda }}</section>\n'
               '  <div class="panel-links">\n'
               '    <a class="button secondary" href="/admin/dashboard">Volver a Pedidos</a>\n'
               '    <a class="button secondary" href="/admin/scanner-diagnostico" target="_blank">Diagnóstico OCR</a>\n'
               '  </div>\n'
               '</main>\n'
               '</body>\n'
               '</html>\n'}

SCANNER_CSS = "*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f3f5f7;color:#17212b}\n.container{max-width:780px;margin:50px auto;padding:20px}.subtitle{color:#5f6b76}.card{background:white;padding:25px;border:1px solid #d8dfe6;border-radius:15px;box-shadow:0 5px 18px rgba(0,0,0,.05)}\nlabel{display:block;font-weight:700;margin-bottom:10px}input[type=file]{display:block;width:100%;padding:12px;border:1px solid #bec8d1;border-radius:9px;margin-bottom:16px}\nbutton,.button{display:inline-block;border:0;border-radius:9px;padding:12px 16px;background:#176b43;color:white;text-decoration:none;font-weight:700;cursor:pointer}.secondary{background:#e7edf1;color:#17212b}\n.info{margin:20px 0;padding:15px;background:#e9f6ef;border-left:5px solid #176b43}.table-page{padding:15px;overflow:auto}\n.toolbar{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:15px;position:sticky;left:0}.buttons{display:flex;gap:8px;flex-wrap:wrap}\ntable{border-collapse:collapse;background:white;min-width:1850px;width:100%}th,td{border:1px solid #d5dde4;padding:7px}th{background:#edf1f4;position:sticky;top:0}\ntd input,td select{width:100%;padding:9px;border:1px solid #b9c4ce;border-radius:7px;font-size:15px}td:nth-child(6) input{min-width:230px}td:nth-child(8) input{min-width:230px}td:nth-child(9) input{min-width:270px}td:nth-child(10) input{min-width:390px}\ntr.warning{background:#fff4d6}#message{font-weight:700;color:#176b43;position:sticky;left:0}.error{border-left:6px solid #b42318}pre{white-space:pre-wrap;background:#101820;color:white;padding:12px;border-radius:8px;overflow:auto}\n\n.calibration-page{max-width:1500px;margin:20px auto;padding:16px}.calibration-header{display:flex;justify-content:space-between;align-items:center;gap:20px}.calibration-legend{display:flex;gap:20px;flex-wrap:wrap;margin:12px 0;font-weight:700}.image-stage{position:relative;width:100%;overflow:hidden;background:#fff;border:2px solid #17212b;touch-action:none}.image-stage img{display:block;width:100%;height:auto}.guide{position:absolute;top:0;bottom:0;width:4px;background:#d92d20;cursor:ew-resize;transform:translateX(-2px);z-index:4}.guide:before{content:'';position:absolute;left:-9px;top:0;width:22px;height:100%}.guide b{position:absolute;top:5px;left:7px;background:#d92d20;color:#fff;padding:4px 7px;border-radius:5px;font-size:12px;white-space:nowrap}.guide-second{background:#b54708}.guide-second b{background:#b54708}.guide-observation{background:#175cd3}.guide-observation b{background:#175cd3}.calibration-form{margin-top:16px}.warning td{background:#fff4d6}\n@media(max-width:760px){.calibration-header{align-items:flex-start;flex-direction:column}.guide b{font-size:10px;padding:3px}}\n.excel-update{position:sticky;left:0;max-width:760px;margin:20px 0;padding:20px;background:#fff;border:2px solid #176b43;border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.10)}\n.excel-update h2{margin-top:0}.excel-update input[type=file]{background:#f7f9fa}\n\n/* Navegación unificada del panel administrador */\n.admin-nav{position:sticky;top:0;z-index:50;display:flex;align-items:center;gap:8px;padding:10px 18px;background:#101828;border-bottom:1px solid #344054;box-shadow:0 2px 10px rgba(0,0,0,.12)}\n.admin-nav a{color:#d0d5dd;text-decoration:none;font-weight:800;padding:10px 14px;border-radius:9px;transition:.15s background,.15s color}\n.admin-nav a:hover{background:#344054;color:#fff}.admin-nav a.active{background:#175cd3;color:#fff}.admin-nav .logout{margin-left:auto;background:#344054;color:#fff}\n.system-kicker{font-size:12px;letter-spacing:.08em;font-weight:900;color:#175cd3;margin-bottom:6px}.panel-links{display:flex;gap:8px;flex-wrap:wrap}\n.systems{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:24px}.system-card{background:#fff;border:2px solid #d8dfe6;border-radius:16px;padding:28px;text-align:center;box-shadow:0 6px 20px rgba(0,0,0,.06)}.system-card h2{margin:0 0 8px}.system-card p{color:#5f6b76}.badge{display:inline-block;font-size:12px;font-weight:800;padding:4px 10px;border-radius:999px;margin-bottom:10px}.badge.talma{background:#e9f6ef;color:#176b43}.badge.policia{background:#e8eef7;color:#1a365d}.system-card.policia{border-color:#1a365d}\n@media(max-width:700px){.admin-nav{overflow-x:auto;padding:8px}.admin-nav a{white-space:nowrap;padding:9px 11px}.admin-nav .logout{margin-left:0}.systems{grid-template-columns:1fr}}\n"
